####################
# connect to mysql #
####################
  spring:
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties: 
        hibernate: 
          dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
      url: jdbc:mysql://localhost:13306/firstdb?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: KefaNaKona
      driver-class-name: com.mysql.jdbc.Driver

#vyzera tot ak ze application.yml vyzaduje datasource.url zacinajuce "jdbc:mysql:"  a nie "dbc:mysql"
#  ktore stacilo application.properties aj ked rozdiel je iba vo formate dat takze nerozumiem preco

###########
# logging #
###########
  logging:
    pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level.org.hibernate.SQL: info

##############################################################################################
############################### original application.properties ##############################
##############################################################################################
##==== connect to mysql ======#
#spring.jpa.hibernate.ddl-auto=create-drop
##spring.datasource.url=jdbc:mysql://localhost:3306/mysqltutorial?useSSL=false
##spring.datasource.url=jdbc:mysql://localhost:13306/firstdb?useSSL=false
#spring.datasource.url = jdbc:mysql://localhost:13306/firstdb?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=KefaNaKona
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#
## logging
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
#logging.level.org.hibernate.SQL=debug
